% Create a horn antenna
% Generated by MATLAB(R) 23.2 and Antenna Toolbox 23.2.
% Generated on: 08-Feb-2025 09:52:58

%% Antenna Properties 

antennaObject = design(horn, 5000*1e6);
antennaObject.FlareLength = 0.09;
antennaObject.FlareWidth = 0.15;
antennaObject.FlareHeight = 0.1;
antennaObject.Length = 0.1;
antennaObject.Conductor.Name = 'Aluminium';
antennaObject.Conductor.Conductivity = 3.77*1e7;
antennaObject.Conductor.Thickness = 0.000762;
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 5*1e9;
% Define frequency range 
freqRange = (4500:50:5500)*1e6;
% Reference Impedance 
refImpedance = 50;
% impedance
figure;
impedance(antennaObject, freqRange)
% sparameter
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)
% pattern
figure;
pattern(antennaObject, plotFrequency)
% azimuth
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)
% elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)
% current
figure;
current(antennaObject, plotFrequency)

