% Create a yagiUda antenna
% Generated by MATLAB(R) 23.2 and Antenna Toolbox 23.2.
% Generated on: 20-Jan-2025 15:09:50

%% Antenna Properties 

antennaObject = design(yagiUda, 1200*1e6);
antennaObject.Exciter= dipoleFolded;
antennaObject.Exciter.Length = 0.10887;
antennaObject.Exciter.Width = 0.0027731;
antennaObject.Exciter.Spacing = 0.001424;
antennaObject.NumDirectors = 9;
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 1200*1e6;
% Define frequency range 
freqRange = (1080:12:1320)*1e6;
% Reference Impedance 
refImpedance = 50;
% impedance
figure;
impedance(antennaObject, freqRange)
% sparameter
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)
% pattern
figure;
pattern(antennaObject, plotFrequency)
% azimuth
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)
% elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)

